baseURL = "https://blog.nightmared.fr/"
languageCode = "en-us"
title = "nightmared's rambles"
theme = "yaht"

[author]
    name = "Simon THOBY"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "colorful"

[permalinks]
  posts = "/posts/:slug"

[menu]
  #[[menu.nav]]
  #  name = "The void"
  #  pre = "home"
  #  url = "https://nightmared.fr"
  #  weight = 1
  [[menu.nav]]
    name = "Blog"
    pre = "edit-2"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "RSS"
    pre = "rss"
    url = "/posts/index.xml"
    weight = 3
  [[menu.nav]]
    name = "About"
    pre = "crosshair"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "Contact"
    pre = "mail"
    url = "/contact/"
    weight = 5
  [[menu.nav]]
    name = "Github"
    pre = "github"
    url = "https://github.com/nightmared"
    weight = 6


[markup]
  [markup.tableOfContents]
    endLevel = 4

[params]
footerText = "It's turtles all the way down - https://github.com/nightmared/site-perso"
dateFormat = "2 January 2006 at 15:04 (CET)"
